### ISSUE TITLE
Load the credentials configuration from the config-security.yaml file

### ISSUE THREAD

**Issue by developerhelperhub** [developerhelperhub/klight-api-gateway#10]
As security, we have to configure all credentials of api gateway services in the 'config-security.yaml' file instead of 'config.yaml' file. This helps to key security file to store into secret vault in the Kubernetes service, `config.yaml' configuration can be configured in the config-map in the Kubernetes service

**Acceptance Criteria**
- Load the 'mongo db' and 'openid' credentials in the 'config-security.yaml' file
- Load the configuration from 'config.yaml' file if the 'config-security.yaml' file not found

**Comment by developerhelperhub** [comment]
Implemented the following functionality

- Default configuration loaded from 'config.yaml' file
- Load the configurations from `configu-security.yaml' file
- Override the configurations from `config.yaml` file if the configuration present in the `configu-security.yaml' file

Example `config.yaml`
```yaml
mongodb:
  host: localhost
  port: 27017
  db: klight-api-gateway
  connection_pool_size: 1

openid:
  discovery_url: "http://127.0.0.1:8084/realms/klight-api-gateway/.well-known/openid-configuration"
  validate_scope: false
  flow_type: introspection
  introspection_endpoint: "http://127.0.0.1:8084/realms/klight-api-gateway/protocol/openid-connect/token/introspect"
```

Example `config-security.yaml`
```yaml
mongodb:
  username: klight-api-gateway
  password: klight-api-gateway

openid:
  client_id: klight-api-gateway-openid-connect
  client_secret: TYxTbrLzFagelYymONmgmSVfueiJnckT

```
