### ISSUE TITLE
Build auth api for authentication with authorise_code flow auth2

### ISSUE THREAD

**Issue by developerhelperhub** [developerhelperhub/klight-api-gateway#17]
As an API gateway implementing the Authorization Code Flow of OAuth2, we need to create APIs that authenticate with the Keycloak server. With this approach, there is no need to implement or maintain session management to check if a user is authenticated when calling upstream server APIs. Instead, when communicating with the upstream server, we only need to validate the request using Keycloak's introspection API.

**Acceptance Criteria**
- Build an API /oauth2/authoirse to authenticate with Keyclock server
- Get the access token, expire time, id token, refresh token
- Use the introspection API call to validate the token when we call upstream server API

**Comment by developerhelperhub** [comment]
Implemented the new endpoint to authenticate and get the tokens from Keycloack

- Implemented new endpoint "/oauth2/authoirse"
- Changed the callback url "/oauth2/callback"
- Changed the introspection configuration
- Store session state in the redis server
- Support redis server configuration, load redis server object, support connection pool

**Introspection Configuration**
New changes in the introspection validation
```yaml
openid:
  discovery_url: "http://127.0.0.1:8084/realms/klight-api-gateway/.well-known/openid-configuration"
  client_id: klight-api-gateway-openid-connect-authorize-code
  client_secret: iO2tmN0XvGfG7RpbANewVB78ZTZMPylP
  flow_type: authorization_code
  ssl_verify: "no"
  session_secret: "jjjjOjjl*nnnPPPPP767"
  token_validation: 
    type: introspection
    endpoint: http://127.0.0.1:8084/realms/klight-api-gateway/protocol/openid-connect/token/introspect
```

**Authentication configuration for authorise code flow**
```yaml
openid:
  discovery_url: "http://127.0.0.1:8084/realms/klight-api-gateway/.well-known/openid-configuration"
  client_id: klight-api-gateway-openid-connect-authorize-code
  client_secret: iO2tmN0XvGfG7RpbANewVB78ZTZMPylP
  flow_type: authorization_code
  ssl_verify: "no"
  session_secret: "jjjjOjjl*nnnPPPPP767"
  token_validation: 
    type: introspection
    endpoint: http://127.0.0.1:8084/realms/klight-api-gateway/protocol/openid-connect/token/introspect
  authentication:
    flow_type: authorization_code
    validate_scope: true
    scope: "openid email profile"
    redirect_uri: "/oauth2/callback"
    redirect_uri_scheme: http
```

Redis server configuration
```yaml
redis:
  host: 127.0.0.1
  port: 6379
  connection_timeout: 1000
  pool_idle_timeout: 10000
  pool_size: 100
```
