### ISSUE TITLE
Enable the SSL / HTTPS API gateway

### ISSUE THREAD

**Issue by developerhelperhub** [developerhelperhub/klight-api-gateway#19]
As security, we have to enabled the SSL / HTTPS communications for API gateway

**Acceptance Criteria**
- Create the SSL certificates for API gateway
- Enable the HTTPS configuration API gateway

**Comment by developerhelperhub** [comment]
Enabled the HTTPS with localhost self signed certificate

Following yaml configuration changed
```yaml
openid:
  ssl_verify: "yes".    #enabled ssl
  authentication:
    redirect_uri_scheme: https   #enabled https
```

[Open SSL generation doc](https://github.com/developerhelperhub/klight-api-gateway/wiki/OpenSSL-Create-Self-Signed-Certificate-Localhost)
