### ISSUE TITLE
Redis server username and password configuration

### ISSUE THREAD

**Issue by developerhelperhub** [developerhelperhub/klight-api-gateway#21]
As security, we have to connect the redis server with username and password.

**Acceptance Criteria** 
- Install redis server username and password
- Connect the redis server with username and password
- Session connection of redis server with username and password

**Comment by developerhelperhub** [comment]
Implemented the logic for accessing redis server with username and password

Configuration YAML
```yaml
redis:
  host: 127.0.0.1
  port: 6379
  connection_timeout: 1000
  pool_idle_timeout: 10000
  pool_size: 100
  username: klight-redis-user
  password: klight-redis-pass
```

[ACL document added](https://github.com/developerhelperhub/klight-api-gateway/wiki/Redis-Cli-Command) 
[Doc Set master password](https://github.com/developerhelperhub/klight-api-gateway/wiki/Redis-Setup-Locally)
