### ISSUE TITLE
Override the openid discovery endpoints

### ISSUE THREAD

**Issue by developerhelperhub** [developerhelperhub/klight-api-gateway#29]
As discovery of authentication flow, we have to override the discovery endpoints based on the configuration in the `config.yaml` file. It helps us to change the endpoints based on our needs, for example if we need to call the endpoint of keycloak internally instead of calling through outside. 

**Acceptance Criteria**
- Add the configuration of discovery in the `config.yaml`
- Load the discovery endpoints and override from the configuration

**Comment by developerhelperhub** [comment]
Implemented the logic to override the openid URL based on the config file. 

```yaml
openid:
  discovery:
    url: "http://127.0.0.1:8080/realms/klight-api-gateway/.well-known/openid-configuration"
    token_endpoint: "http://127.0.0.1:8080/realms/klight-api-gateway/protocol/openid-connect/token"
    issuer: http://127.0.0.1:8080/realms/klight-api-gateway
    authorization_endpoint: http://127.0.0.1:8080/realms/klight-api-gateway/protocol/openid-connect/auth
    jwks_uri: http://127.0.0.1:8080/realms/klight-api-gateway/protocol/openid-connect/certs
    userinfo_endpoint: http://127.0.0.1:8080/realms/klight-api-gateway/protocol/openid-connect/userinfo
    introspection_endpoint: http://127.0.0.1:8080/realms/klight-api-gateway/protocol/openid-connect/token/introspect
    end_session_endpoint: http://127.0.0.1:8080/realms/klight-api-gateway/protocol/openid-connect/logout

  flow_type: authorization_code
  ssl_verify: "yes"
  token_validation: 
    type: introspection
  authentication:
    flow_type: authorization_code
    validate_scope: true
    scope: "openid email profile"
    redirect_uri: "/oauth2/callback"
    redirect_uri_scheme: http
```

**Implementation**
* `discovery.url`: mandatory configuration
* all other endpoints are optional
* First, API gateway pull the discovery endpoint from discovery url, if any endpoint is configured in the configuration, that endpoint will be override based on configuration file
* Cached the discovery response
