### ISSUE TITLE
Configure the mongo db as primary storage

### ISSUE THREAD

**Issue by developerhelperhub** [developerhelperhub/klight-api-gateway#4]
As an API gateway, we need to store configurations in MongoDB, allowing the gateway to connect to the database for easy configuration retrieval.

**Acceptance Criteria**

- Run MongoDB locally using Docker.
- Establish a connection to MongoDB.
- Load MongoDB configurations from the configuration file.
- Implement support for a connection pool.

**Comment by developerhelperhub** [comment]
**Implementation details**

- Connection pool created while start server each, worker (CPU core) will be created db objects based on pool size default 4, for example 4 core cpu * pool size 4 = 16 pools
- Loaded the mongo configuration from `config.yaml`
- Created the repository module for "services" to list all services, find the all items from the collection "services" in mongo db
- Loaded the services in the "reverse_proxy.lua"

**Mongo Configuration Example**
```
mongodb:
  host: "localhost"
  port: 27017
  db: klight-api-gateway
  username: "klight-api-gateway"
  password: "klight-api-gateway"
```
